### ISSUE TITLE
Improve folding

### ISSUE THREAD

**Issue by camilstaps** [camilstaps/vim-clean#6]
Goals:

- Foldable (nested) where/with blocks
- Being able to fold constructors and records
- Being able to fold normal functions
- Not folding indented guards and lets - at the point that this becomes useful your function is too long

Inspiration: https://github.com/Twinside/vim-haskellFold/blob/master/plugin/haskellFold.vim

**Comment by mklinik** [comment]
The last point, "at the point that this becomes useful your function is too long" is interesting. When then is folding ever useful? I'm struggling to find uses for folding. At the moment I think one should write code that is readable without folding. What do you think?

**Comment by camilstaps** [comment]
@mklinik I was thinking of functions like [this](https://github.com/clean-cloogle/Cloogle/blob/89d95f7aa03b04d0cea3c8cf369f0a529c0c6aa7/Search.icl#L29). It is way too long, imperative spaghetti style (it should, one day, be rewritten to a writer monad). Somebody may think he wants to fold that code, but what he should actually want is breaking this up into smaller pieces and abstract away duplicate code.

Similarly, code with many nested guards means having many branch points; it makes the code ununderstandable. An example of what I think of is [here](https://git.martlubbers.net/?p=fp1415-soccerfun.git;a=blob;f=src/Team_MartLubbers.icl;h=0b2410f9f266111ede1b2548697232fbce5c931f;hb=refs/heads/master#l77). Instead of collapsing the guards, the programmer should move parts of it to the where clause (e.g., making three different local functions for keeper, defense and attacker) and then they can fold the where clause.

So essentially I agree that "one should write code that is readable without folding" when it concerns `#` and guards.

The reason I don't want to support folding on guards and lets is that this would make it difficult to correctly handle cases where the second and further lines of a function is indented to look nice, e.g. [here](https://github.com/clean-cloogle/Cloogle/blob/89d95f7aa03b04d0cea3c8cf369f0a529c0c6aa7/CloogleDBFactory.icl#L86). It would be difficult to fold guards and lets but not fold this (which I don't think it should be, except for on the top level where it would be nice to fold the whole function).

I *do* see a use in where clause folding though. Take as an example [this function](https://github.com/clean-cloogle/Cloogle/blob/89d95f7aa03b04d0cea3c8cf369f0a529c0c6aa7/CloogleDBFactory.icl#L189), and in particular the nested where clauses of `pd_classes` and `pd_rewriterules`. There I would like to be able to fold those blocks, because they are really only interesting when working on the implementation of the functions themselves. When working outside of the block, the type of `pd_rewriterules` (e.g.) is enough to understand what it does. Similarly, when I'm working on `indexModule`, I might be interested in the top level of `findModuleContents` but not in its where clauses.

The reason I want to be able to fold normal functions (I imagine that the whole function is hidden and the `foldtext` shows the signature) is that it allows you to have more information of the API on one screen when working on new functions that might use different parts of that API.

The reason I want to be able to fold ADT and record type definitions is for example the `Token` type [in the Clean compiler](https://svn.cs.ru.nl/repos/clean-compiler/trunk/frontend/scanner.dcl).

I believe that the following description summarises my current idea well:

- We fold on indentation level;
- The `where` and `with` keywords are considered to be one level lower than their actual indentation level, so that they are at the same level as their code block;
- The indentation of function bodies (plain code, `#` and guards) is considered equal to that of the function signature / first line;
- When indenting with a special amount of characters to match up `=` tokens or so, this should be considered one indent level so that you only have to open one fold.

But I also realise that others may have different preferences; in that case we can hopefully support different styles through options.

Note that from what length of code block folding becomes interesting is a personal preference; it can be set with `foldminlines`.
